### ISSUE TITLE
[Bug]: SSMS fails to install with error 0x80070654

### ISSUE THREAD

**Issue by jannikk09** [svrooij/WingetIntune#50]
### Command

package

### Full command

wintuner package Microsoft.SQLServerManagementStudio --package-folder 

### App version

0.8.3+5223c56ae709364a27c44196b5873379a8bac500

### What happened?

I tried to install SSMS over Intune. 
I created the files over Wintuner. The installation fails with this code "0x80070654".

### Command output

```Shell
The command works and the files are created correctly
```

### Windows version and current language

Windows 11 - German

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
@jannikk09 they have a custom installer for SSMS (.exe instead of a regular .msi).
It's not so much that WinTuner does not work, it works as expected in my opinion, the installer does not complete (successfully) in this case.

Does it work when you execute `winget install {packageId} --silent` on the machine?

If that is the case I might be able to create an extra option where it will just package a script that executes the Winget command. This is by far not the preferred way, because it relies upon downloading the installer from a remote source and not from Intune (content distribution and such).

**Comment by jannikk09** [comment]
I can install via winget install... 
Could you change it?

**Comment by svrooij** [comment]
This is an open-source project that I built in my spare time, which I don't have a lot, at the moment. Cannot make any promises when I can implement this
